services:
  juicy-check:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6067:5173"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
